// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed:"node prisma/seed.js"
  },
  datasource: {
    url: "postgresql://postgres.plckhiwibtavxjjvyzpi:une.ddti2024@aws-1-us-east-1.pooler.supabase.com:5432/postgres"
  },
});
